### ISSUE TITLE
No sync/resync button

### ISSUE THREAD

**Issue by nolan-interactive** [plesk/ext-slave-dns-manager#25] opened 2017-10-05 03:49 UTC
There is no sync or resync button.

Plesk Windows 12.0.18 Update #79
Slave DNS Manager (latest)

**Comment by vlikhtanskiy** [comment] 2017-10-05 03:55
This button is available only for Plesk Onyx because resync backend was introduced in that version.

**Comment by ayamshanov** [comment] 2018-04-20 07:45
I close the issue because it is not a bug, it is a limitation of Plesk 12.x. I suggest updating Plesk to get 'Resync" button.

**Closed by ayamshanov** 2018-04-20 07:45 UTC
